name: 'Deploy to Admin Portal'

inputs:
 tminstance:  # id of input
  description: Environment name
  required: true 

    
runs:
  using: "composite"  
  steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: dispaly instance name
      run: |
       echo ${{ inputs.tminstance }}
      shell: bash

    - name: Deploy war1
      run: |   
       echo "Deployed war1"
      shell: bash

    - name: Deploy war2
      run: |   
        echo "Deployed war2"
      shell: bash

    - name: Deploy war3
      run: |   
        echo "Deployed war3"
      shell: bash
        
    - name: Deploy war4
      run: |   
        echo "Deployed war4"
      shell: bash
