name: deploy-sit

on:
    workflow_dispatch: 

jobs:
    deploy-sit-admin:
        strategy:
            matrix:
                instances: [SIT_ADMIN_TOMCAT1, SIT_ADMIN_TOMCAT2]
        uses: ./.github/workflows/deploy-admin-reusable.yml
        with:
          ENVIRONMENT: SIT
          TOMCAT_INSTANCE: ${{ matrix.instances }}        
        secrets: inherit

    deploy-sit-customer:
        strategy:
            matrix:
                instances: [SIT_CUSTOMER_TOMCAT1, SIT_CUSTOMER_TOMCAT2]
        uses: ./.github/workflows/deploy-customer-reusable.yml
        with:
          ENVIRONMENT: SIT
          TOMCAT_INSTANCE: ${{ matrix.instances }} 
        secrets: inherit
