name: deploy-sit

on:
    workflow_dispatch: 

jobs:
    deploy-sit-admin:
        environment: SIT
        runs-on: ubuntu-latest
        strategy:
            matrix:
                insances: [tminst1, tminst2]               

        steps:
            - uses: actions/checkout@v3
              with:
                persist-credentials: false

            - name: Deploy war1
              run: |   
                echo "Deployed war1"

            - name: Deploy war2
              run: |   
                echo "Deployed war2"

            - name: Deploy war3
              run: |   
                echo "Deployed war1"

            - name: Deploy war4
              run: |   
                echo "Deployed war4"

    deploy-sit-customer:
        environment: SIT
        runs-on: ubuntu-latest
        strategy:
            matrix:
                insances: [tminst1, tminst2]               

        steps:
            - uses: actions/checkout@v3
              with:
                persist-credentials: false

            - name: Deploy war1
              run: |   
                echo "Deployed war1"

            - name: Deploy war2
              run: |   
                echo "Deployed war2"

            - name: Deploy war3
              run: |   
                echo "Deployed war3"

           

