# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
 workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     registry-url: https://npm.pkg.github.com/
      - run: |
          npm i
        env: 
          PAT: ${{secrets.PAT}}
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
      # - name: Download npm-proj package using PAT
      #   run: |
      #     npm pack --registry=https://npm.pkg.github.com @sudarsana-reddy/npm-proj
      #     tar -xf *.tgz
      #     ls -ltr
      #     cd package
      #     ls -ltr
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.PAT}}
      - run: node index.js
