name: Release Download Asset

on:
  workflow_dispatch:        

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Downlaod Release Asset Action
        run: |
          git clone https://${{ secrets.PAT }}@github.com/sudarsana-reddy/download-release-asset.git
                  
      - name: Download Release file
        uses: ./download-release-asset
        env:         
          PACKAGE_SCOPE_NAME: ${{vars.PACKAGE_SCOPE_NAME}}  
          SDK_RELEASE_REPO: ${{vars.SDK_RELEASE_REPO}}
          PAT: ${{secrets.PAT}}

      - name: Check File System
        run: ls -ltr         
        shell: bash
        
