name: Release Download Asset

on:
  workflow_dispatch:        

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Releae file
        run: |        
          echo Trying to get the release assets 
          response=$(curl -L "https://api.github.com/repos/sudarsana-reddy/npm-empty-proj/releases/tags/$RELEASE_VERSION" -H "Authorization: Bearer $PAT" )
          echo "*****************************************"
          echo "Extracting the asset URL"
          url=$(echo "$response" | jq .assets | jq '.[] | select(.name=="abcd.zip") | .url')
          echo "$url"
          echo "Sanitizing URL"
          asset_url=$(echo $url | tr -d '"')
          echo "$asset_url"
          echo  "***************************************"
          echo "Downloading Release Asset"
          curl -o ./"$SDK_FILE_NAME" -w "%{http_code}" -H "Authorization: Bearer $PAT" -H "Accept: application/octet-stream" -L "$asset_url"
        shell: bash
        env:
          RELEASE_VERSION : ${{vars.RELEASE_VERSION}}
          SDK_FILE_NAME: ${{vars.SDK_FILE_NAME}}
          PAT: ${{secrets.PAT}}

      - name: Check the download
        run: |
            ls -ltr          
    
