name: Release Download Asset

on:
  workflow_dispatch:        

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Releae file
        run: sh ./download-here-sdk.sh          
        shell: bash
        env:         
          PACKAGE_SCOPE_NAME: ${{vars.PACKAGE_SCOPE_NAME}}  
          SDK_RELEASE_REPO: ${{vars.SDK_RELEASE_REPO}}
          PAT: ${{secrets.PAT}}
