name: "Test NPM local reference"

permissions: 
    contents: write

on:
    workflow_dispatch:

jobs:
    execute:
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
              uses: actions/checkout@v4

            - name: list repo folders
              run: |
                pwd
                ls -ltr

            - name: download the dependency
              run: |
                mkdir lib
                ls -ltr
                cd lib
                ls -ltr
                curl -L -H "Authorization: Bearer ${{ secrets.PAT }}" -O ${{vars.DEPENDENCY_URL}}
                ls -ltr

            - name: npm install
              run: |
                npm install

            - name: Run code
              run: |
                node index.js
            
            
